### ISSUE TITLE
IPD is not capitalized

### ISSUE THREAD

**Issue by nlhepler** [PacificBiosciences/PacBioFileFormats#42]
But it is in {bas,cmp}.h5. This introduces incompatibilities in our API. Well done us.

Now you have to check, e.g. ("IPD" in alnFile.baseFeaturesAvailable() or "Ipd" in alnFile.baseFeaturesAvailable())

**Comment by nlhepler** [comment]
@aklammer @dalexander please advise

**Comment by pbjd** [comment]
Why not make it a case-insensitive match?

**Comment by aklammer** [comment]
case-insensitive seems reasonable to me.

**Comment by nlhepler** [comment]
We need to establish convention. None of the languages we use are case-insensitive. We need to transform them in our APIs, and note this is a breaking API change.

**Comment by pbjd** [comment]
So this would cover all BAM tags specifically.  I would argue for all lower, since not everything is an acronym.  So what would the blast radius of this be?  Usual suspects: Documentation update, other method calls within the API, callers of the API, version compatibility issues.

**Comment by nlhepler** [comment]
It's not just tags: more specifically it's the feature list in the BAM header (and the corresponding datasets in the {ba[sx],cmp}.h5)

**Comment by aklammer** [comment]
So that would result in a call that looks like e.g. "ipd" in alnFile.baseFeaturesAvailable() ?

If we're breaking the API already, would adopting something that avoided magic strings like "IPD" or "Ipd" help here? i.e. replace the above API calls with alnFile.hasIPD() or similar? This may increase the blast radius unacceptably.

**Comment by dalexander** [comment]
Per discussion with Lance, I don't think we should make any change to the spec, but if we want, we can 

I agree this is somewhat unfortunate.  But there was never really intended to be a 1:1 mapping from tag/feature names to APIs.  The APIs should be where we focus on making the interface uniform.  So while the BAM/cmp.h5 files may have differ spellings, it's on us to protect the APIs from this.  

Lance has also suggested that since we probably will not be supporting cmp.h5 that much longer, it may not be worth dwelling on this point, or doing anything here.

I'm going to close this issue, and if Lance feels motivated, he could reopen an issue in pbcore.
